name: Vercel Blob Backup to Dropbox
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dropbox requests python-dateutil
          
      - name: Run backup script
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          BACKUP_FOLDER_NAME: ${{ vars.BACKUP_FOLDER_NAME || 'vercel-blob-backups' }}
          RETENTION_DAYS: ${{ vars.RETENTION_DAYS || '7' }}
        run: python .github/scripts/backup_script.py
